language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install .
- pip install flake8
- pip install future
- pip install PyOpenSSL
script:
- flake8 --ignore=E501 --exclude=__init__.py .
- pushd /tmp && python -c 'import pypinksign' && popd