language: python
sudo: false
python:
- pypy
- 2.6
- 2.7
install:
- pip install .
- pip install flake8
script:
- flake8 --ignore=E501 --exclude=__init__.py .
- pushd /tmp && python -c 'import pypinksign' && popd